name: makie-demo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - julia=1.10                # Julia runtime
  - pip
  - pip:
      - fastapi[all]==0.111.0
      - uvicorn
      - juliacall==0.9.2
      - python-dotenv          # optional, for .env files